
enum TokenType
{
	MAIN = 258, DOUBLE, INTEGER, ID, IF, THEN, ELSE, END, REPEAT, FLOAT, VOID, UNTIL, READ, WRITE, RETURN, INT, EXP, PLUS, MINUS, TIMES, OVER, EQUAL, 
     COMMA, LT, LT_EQUAL, RT, RT_EQUAL, LPARENT, RPARENT, SEMICOLON, ASSIGN, LINE_BREAK, ERROR, FINISH
};